version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_KEY: api_key
        VITE_HOST_IP: 2.56.244.117
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - VITE_API_KEY=api_key
      - MYSQL_ROOT_PASSWORD=root
      - VITE_HOST_IP=2.56.244.117

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3001:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: 
