version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_KEY=api_key
    depends_on:
      - server
    networks:
      - my-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - VITE_API_KEY=api_key
      - MYSQL_ROOT_PASSWORD=root

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3001:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

volumes:
  db_data: 

networks:
  my-network:
