services:
  client:
    image: headlessdev0/admindata-server:latest
    ports:
      - "3000:80"
    environment:
      - VITE_HOST_IP=${VITE_HOST_IP}
    depends_on:
      - server

  server:
    image: headlessdev0/admindata-server:latest
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app/db

volumes:
  db_data: