services:
  client:
    image: damiandbergemann278/admindata-client:latest
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://<YOUR_IP>:5000
    depends_on:
      - server
    restart: always
  server:
    image: damiandbergemann278/admindata-server:latest
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app/db
    environment:
      - CLIENT_URL=http://<YOUR_IP>:3000
    restart: always
volumes:
  db_data: