services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_HOST_IP: ${VITE_HOST_IP}
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app/db

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - db_data:/app/db

volumes:
  db_data: