services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        CLIENT_URL: ${CLIENT_URL}
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app/db
volumes:
  db_data: